# Docker compose file for the application.

#version: '2'   # on CircleCI the version and services cause build to puke.
#services:

  app:
    build: .
    dockerfile: ./deploy/app/Dockerfile
    environment:
     - ELASTICSEARCH_URL=http://localhost:9200
    links:
     - elasticsearch
    ports:
     - "8000:80"

  elasticsearch:
    build: .
    dockerfile: ./deploy/elasticsearch/Dockerfile
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
     - "9200:9200"
     - "9300:9300"
